data = [
    {"name": "Twitter", "search_count": 72, "description": "Social Networking Service", "country": "United States"},
    {"name": "YouTube", "search_count": 95, "description": "Video Sharing Platform", "country": "United States"},
    {"name": "Samsung", "search_count": 90, "description": "Electronics Manufacturer", "country": "South Korea"},
    {"name": "Taj Mahal", "search_count": 89, "description": "Historical Monument", "country": "India"},
    {"name": "Great Wall of China", "search_count": 92, "description": "Historical Monument", "country": "China"},
    {"name": "New York City", "search_count": 87, "description": "Major City", "country": "United States"},
    {"name": "Apple", "search_count": 96, "description": "Tech Company", "country": "United States"},
    {"name": "Nike", "search_count": 81, "description": "Sportswear Company", "country": "United States"},
    {"name": "Microsoft", "search_count": 94, "description": "Tech Company", "country": "United States"},
    {"name": "Amazon", "search_count": 98, "description": "E-commerce Giant", "country": "United States"},
    {"name": "Taylor Swift", "search_count": 85, "description": "Musician and Singer-Songwriter", "country": "United States"},
    {"name": "Cristiano Ronaldo", "search_count": 91, "description": "Footballer", "country": "Portugal"},
    {"name": "Leonardo DiCaprio", "search_count": 82, "description": "Actor", "country": "United States"},
    {"name": "BTS", "search_count": 88, "description": "Music Band", "country": "South Korea"},
    {"name": "Bagan", "search_count": 97, "description": "World Heritage Site", "country": "Myanmar"},
    {"name": "Mount Everest", "search_count": 93, "description": "Highest Mountain in the World", "country": "Nepal"},
    {"name": "Oprah Winfrey", "search_count": 86, "description": "Talk Show Host and Media Mogul", "country": "United States"},
    {"name": "The Louvre", "search_count": 90, "description": "World's Largest Museum", "country": "France"},
    {"name": "Lionel Messi", "search_count": 94, "description": "Footballer", "country": "Argentina"},
    {"name": "Eiffel Tower", "search_count": 92, "description": "Famous Landmark", "country": "France"},
    {"name": "Ed Sheeran", "search_count": 83, "description": "Musician and Songwriter", "country": "United Kingdom"},
    {"name": "Scarlett Johansson", "search_count": 80, "description": "Actress", "country": "United States"},
    {"name": "Shah Rukh Khan", "search_count": 87, "description": "Actor", "country": "India"},
    {"name": "Adele", "search_count": 79, "description": "Singer and Songwriter", "country": "United Kingdom"},
    {"name": "Sydney Opera House", "search_count": 84, "description": "World Heritage Site", "country": "Australia"},
    {"name": "Madonna", "search_count": 88, "description": "Singer and Pop Icon", "country": "United States"},
    {"name": "Machu Picchu", "search_count": 91, "description": "Historical Site", "country": "Peru"},
    {"name": "The Colosseum", "search_count": 90, "description": "Historical Landmark", "country": "Italy"},
    {"name": "Kylie Jenner", "search_count": 85, "description": "Entrepreneur and Media Personality", "country": "United States"},
    {"name": "Barack Obama", "search_count": 89, "description": "Former US President", "country": "United States"},
    {"name": "Keanu Reeves", "search_count": 86, "description": "Actor", "country": "Canada"},
    {"name": "Jennifer Lopez", "search_count": 83, "description": "Singer and Actress", "country": "United States"},
    {"name": "Nelson Mandela", "search_count": 94, "description": "Anti-Apartheid Revolutionary", "country": "South Africa"},
    {"name": "Beethoven", "search_count": 80, "description": "Composer", "country": "Germany"},
    {"name": "Gal Gadot", "search_count": 82, "description": "Actress", "country": "Israel"},
    {"name": "Rio de Janeiro", "search_count": 90, "description": "Famous City and Tourist Destination", "country": "Brazil"},
    {"name": "Walt Disney", "search_count": 86, "description": "Animation Pioneer", "country": "United States"},
    {"name": "Billie Eilish", "search_count": 81, "description": "Singer-Songwriter", "country": "United States"},
    {"name": "Giza Pyramids", "search_count": 93, "description": "World Heritage Site", "country": "Egypt"},
    {"name": "Harry Potter", "search_count": 90, "description": "Wizard", "country": "United Kingdom"},
    {"name": "Hogwarts", "search_count": 88, "description": "School of Witchcraft and Wizardry", "country": "United Kingdom"},
    {"name": "Pikachu", "search_count": 94, "description": "Electric-Type Pokémon", "country": "Japan"},
    {"name": "Iron Man", "search_count": 85, "description": "Superhero", "country": "United States"},
    {"name": "Gotham City", "search_count": 82, "description": "City in DC Comics", "country": "United States"},
    {"name": "Frodo Baggins", "search_count": 79, "description": "Hobbit from The Lord of the Rings", "country": "New Zealand"},
    {"name": "Sherlock Holmes", "search_count": 93, "description": "Detective", "country": "United Kingdom"},
    {"name": "Elsa", "search_count": 88, "description": "Disney Princess from Frozen", "country": "United States"},
    {"name": "The Shire", "search_count": 87, "description": "Hometown of Hobbits", "country": "New Zealand"},
    {"name": "Super Mario", "search_count": 92, "description": "Video Game Character", "country": "Japan"},
    {"name": "Wonder Woman", "search_count": 86, "description": "Amazonian Superhero", "country": "United States"},
    {"name": "Darth Vader", "search_count": 89, "description": "Star Wars Villain", "country": "United States"},
    {"name": "Springfield", "search_count": 80, "description": "Town in The Simpsons", "country": "United States"},
    {"name": "Link", "search_count": 81, "description": "Hero from The Legend of Zelda", "country": "Japan"},
    {"name": "Wakanda", "search_count": 90, "description": "African Nation in Marvel Universe", "country": "United States"},
    {"name": "Hyrule", "search_count": 84, "description": "Kingdom in The Legend of Zelda", "country": "Japan"},
    {"name": "Mickey Mouse", "search_count": 91, "description": "Disney Character", "country": "United States"},
    {"name": "Pandora", "search_count": 87, "description": "World in Avatar", "country": "United States"},
    {"name": "Optimus Prime", "search_count": 85, "description": "Transformer Character", "country": "United States"},
    {"name": "Arendelle", "search_count": 89, "description": "Kingdom from Frozen", "country": "United States"},
    {"name": "Leonardo da Vinci", "search_count": 93, "description": "Renaissance Artist and Inventor", "country": "Italy"},
    {"name": "Coca-Cola", "search_count": 89, "description": "Soft Drink Company", "country": "United States"},
    {"name": "Mount Everest", "search_count": 91, "description": "Highest Mountain in the World", "country": "Nepal/China"},
    {"name": "Amalfi Coast", "search_count": 85, "description": "Coastal Region in Italy", "country": "Italy"},
    {"name": "Al Pacino", "search_count": 90, "description": "Actor", "country": "United States"},
    {"name": "Sagrada Família", "search_count": 94, "description": "Basilica in Barcelona", "country": "Spain"},
    {"name": "Kilimanjaro National Park", "search_count": 88, "description": "National Park in Tanzania", "country": "Tanzania"},
    {"name": "The Louvre Museum", "search_count": 93, "description": "Museum in Paris", "country": "France"},
    {"name": "Bora Bora", "search_count": 87, "description": "Island in French Polynesia", "country": "French Polynesia"},
    {"name": "Mona Lisa", "search_count": 92, "description": "Famous Painting by Leonardo da Vinci", "country": "Italy"},
    {"name": "Malala Yousafzai", "search_count": 86, "description": "Activist for Girls' Education", "country": "Pakistan"},
    {"name": "Taj Mahal", "search_count": 90, "description": "Mausoleum in India", "country": "India"},
    {"name": "Tokyo Tower", "search_count": 85, "description": "Landmark in Tokyo", "country": "Japan"},
    {"name": "Chichen Itza", "search_count": 94, "description": "Ancient Mayan City", "country": "Mexico"},
    {"name": "Freddie Mercury", "search_count": 91, "description": "Musician and Lead Singer of Queen", "country": "United Kingdom"},
    {"name": "Eiffel Tower", "search_count": 89, "description": "Iconic Landmark in Paris", "country": "France"},
    {"name": "Marilyn Monroe", "search_count": 88, "description": "Actress and Model", "country": "United States"}
]
