fruits = [
    "apple",
    "apricot",
    "avocado",
    "banana",
    "bilberry",
    "blackberry",
    "blackcurrant",
    "blueberry",
    "boysenberry",
    "cherry",
    "clementine",
    "coconut",
    "cranberry",
    "currant",
    "date",
    "dragonfruit",
    "durian",
    "elderberry",
    "feijoa",
    "fig",
    "gooseberry",
    "grape",
    "grapefruit",
    "guava",
    "honeyberry",
    "huckleberry",
    "jackfruit",
    "kiwi",
    "kumquat",
    "lemon",
    "lime",
    "lychee",
    "mango",
    "melon",
    "mulberry",
    "nectarine",
    "orange",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "persimmon",
    "pineapple",
    "plum",
    "pomegranate",
    "pomelo",
    "quince",
    "raspberry",
    "rhubarb",
    "salak",
    "satsuma",
    "starfruit",
    "strawberry",
    "tamarillo",
    "tamarind",
    "tangerine",
    "ugli",
    "watermelon",
    "yumberry",
    "jabuticaba",
    "cherimoya",
    "cantaloupe",
    "loquat",
    "longan",
    "carambola",
    "soursop",
    "santol",
    "ackee",
    "breadfruit",
    "bael",
    "chikoo",
    "lanzones",
    "rambutan",
    "sapodilla",
    "rowanberry",
    "bilimbi",
    "medlar",
    "sea-buckthorn",
    "cloudberry",
    "jambul",
    "grumichama",
    "mamoncillo",
    "jaboticaba",
    "lucuma",
    "pitanga",
    "miraclefruit",
    "goji",
    "marula",
    "camu",
    "calamondin",
    "guinep",
    "pequi",
    "mammee",
    "bignay",
    "jaboticaba",
    "tamarindus",
    "kaki",
    "hornedmelon",
    "naranjilla",
]

animals = [
    "ant", "bat", "bear", "bee", "bird", "boar", "bug", "cat", "cod", "cow", "crab", "crow", "deer", 
    "dog", "dove", "duck", "eel", "elk", "fox", "frog", "goat", "hare", "hawk", "hen", "hog", 
    "horse", "koi", "lion", "loon", "lynx", "mole", "moose", "moth", "mouse", "newt", "owl", "ox", 
    "panda", "pig", "pike", "rat", "ray", "seal", "shark", "sheep", "skunk", "slug", "snail", 
    "snake", "squid", "swan", "tiger", "toad", "trout", "tuna", "vole", "wasp", "wolf", "wren", 
    "yak", "zebra", "alpaca", "bison", "camel", "civet", "cougar", "coyote", "dingo", "donkey", 
    "ferret", "finch", "gecko", "gibbon", "gorilla", "guppy", "heron", "jackal", "jaguar", 
    "lemur", "leopard", "llama", "magpie", "manatee", "mantis", "marten", "mink", "monkey", 
    "narwhal", "ocelot", "otter", "puffin", "quail", "rabbit", "raven", "salmon", "sparrow", 
    "stoat", "turkey", "urchin", "vulture", "weasel", "whale"
]
